In [1]:
import numpy as np
import os
import pandas as pd
import cv2
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

In [2]:
dataset = pd.read_csv('./train/train.csv')
dataset

image  category
0     2823080.jpg         1
1     2870024.jpg         1
2     2662125.jpg         2
3     2900420.jpg         3
4     2804883.jpg         2
...           ...       ...
6247  2881056.jpg         3
6248  1145083.jpg         2
6249  2898652.jpg         5
6250  2868175.jpg         3
6251  2784171.jpg         1

[6252 rows x 2 columns]

In [3]:
dataset['category'].describe()

count    6252.000000
mean        2.657550
std         1.528998
min         1.000000
25%         1.000000
50%         2.000000
75%         4.000000
max         5.000000
Name: category, dtype: float64

In [4]:
os.chdir('./train/images/')
os.getcwd()

'd:\\ADG Probation\\Ship classifier\\train\\images'

In [5]:
for dirname, _, filenames in os.walk('./'):
    for filename in filenames:
        print(os.path.join(dirname,filename))

./1001524.jpg
./1001804.jpg
./1003035.jpg
./1004028.jpg
./1004054.jpg
./1005343.jpg
./1007700.jpg
./1008439.jpg
./1010906.jpg
./1011369.jpg
./1011813.jpg
./1013663.jpg
./1014573.jpg
./1015027.jpg
./1016682.jpg
./1016683.jpg
./1019271.jpg
./1048999.jpg
./1049854.jpg
./1051155.jpg
./1056547.jpg
./1056555.jpg
./1059245.jpg
./1062001.jpg
./1062006.jpg
./1069397.jpg
./1072012.jpg
./1072257.jpg
./1072860.jpg
./1072861.jpg
./1073645.jpg
./1079150.jpg
./1084779.jpg
./1095624.jpg
./1097264.jpg
./1098729.jpg
./1098755.jpg
./1098763.jpg
./1098764.jpg
./1098766.jpg
./1101145.jpg
./1106366.jpg
./1112343.jpg
./1114370.jpg
./1114371.jpg
./1114372.jpg
./1114376.jpg
./1114377.jpg
./1114781.jpg
./1115492.jpg
./1119685.jpg
./1119689.jpg
./1120259.jpg
./1120419.jpg
./1121306.jpg
./1123736.jpg
./1124945.jpg
./1124946.jpg
./1124949.jpg
./1124951.jpg
./1124952.jpg
./1124953.jpg
./1125004.jpg
./1125700.jpg
./1126799.jpg
./1127233.jpg
./1127236.jpg
./1127237.jpg
./1127335.jpg
./1127336.jpg
./1130300.jpg
./1131

In [6]:
image_name = dataset['image']
image_name = np.array(image_name)

In [7]:
image_name

array(['2823080.jpg', '2870024.jpg', '2662125.jpg', ..., '2898652.jpg',
       '2868175.jpg', '2784171.jpg'], dtype=object)

In [8]:
label = dataset['category']
label = np.array(label)

In [9]:
label

array([1, 1, 2, ..., 5, 3, 1], dtype=int64)

In [10]:
list = []

for image in image_name:
    im = cv2.imread('./'+image , 1)
    im = cv2.resize(im ,(210,210))
    list.append(im)

list1 = np.array(list)

In [11]:
x_train , x_test , y_train , y_test = train_test_split(list1 ,label , test_size=0.1)
print(x_train.shape , y_train.shape)
print(x_test.shape , y_test.shape)


(5626, 210, 210, 3) (5626,)
(626, 210, 210, 3) (626,)


In [12]:
X_train, X_val, Y_train, Y_val = train_test_split(x_train, y_train, test_size=0.18, random_state=1)
print(X_train.shape , Y_train.shape)
print(x_test.shape , y_test.shape)
print(X_val.shape , Y_val.shape )

(4613, 210, 210, 3) (4613,)
(626, 210, 210, 3) (626,)
(1013, 210, 210, 3) (1013,)


In [13]:
Y_train = to_categorical(Y_train)
print(Y_train.shape)
y_test = to_categorical(y_test)
print(y_test.shape)
Y_val = to_categorical(Y_val)
print(Y_val.shape)

(4613, 6)
(626, 6)
(1013, 6)


In [14]:
print(y_test[0])

[0. 0. 0. 0. 1. 0.]


In [15]:
print(Y_train[0])

[0. 1. 0. 0. 0. 0.]


In [16]:
X_train = X_train/255.0
x_test = x_test/255.0
X_val = X_val/255.0

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D,Dropout, Flatten, MaxPooling2D

In [18]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [25]:


model = tf.keras.models.Sequential()

model.add(Conv2D(32,(3,3), activation='relu', input_shape = (210,210,3)))
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.2))
model.add(Conv2D(16,(3,3), activation='relu'))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(32,(3,3), activation='relu'))
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.2))
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.2))
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPooling2D(2,2))
model.add(Flatten())

model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))

model.add(Dense(6, activation='softmax'))

In [20]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 208, 208, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 104, 104, 32)     0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 104, 104, 32)      0         
                                                                 
 conv2d_1 (Conv2D)           (None, 102, 102, 16)      4624      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 51, 51, 16)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 49, 49, 32)        4

In [26]:
model.compile(loss = 'categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [22]:
!nvidia-smi

Thu Oct  6 00:38:38 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.78       Driver Version: 512.78       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0    16W /  N/A |   2528MiB /  4096MiB |     35%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [27]:
model.fit(X_train , Y_train , epochs=10 , validation_data=(X_val, Y_val), batch_size= 4)

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.

In [ ]:
#model.save_weights("D:\ADG Probation\Ship classifier\weights.pt")

In [ ]:

#model.save('D:\ADG Probation\Ship classifier\model.hdf5')